name: Benchmarks (Comment)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: 
      - Benchmarks
    types:
      - completed
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: lorenzwalthert/touchstone/actions/comment@main
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
